<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- lidar sensors -->
  <property name="thickness_lidar" value="0.041" /> <!-- Thickness of lidar -->
  <property name="diam_lidar"      value="0.076" /> <!-- Angle of lidar     -->
  <property name="mass_lidar"      value="0.1"   /> <!-- Mass of lidar      -->
  
  <property name="base_x_origin_to_lidar_origin" value="0.33000" />
  <property name="base_y_origin_to_lidar_origin" value="0.00000" />
  <property name="base_z_origin_to_lidar_origin" value="0.29350" />
  
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>
  
  <xacro:macro name="lidar" params="fb cnc lrc parent translateX translateY translateZ flipX flipY flipZ"> <!--fb : front, back ; cnc: corner, no corner; lr: left, right -->
    <link name="${fb}_${cnc}_${lrc}_lidar">
      <visual>
        <origin xyz="0 0 0" rpy="${flipX*Pi/180} ${flipY*Pi/180} ${flipZ*Pi/180}"/> 
        <geometry>
          <cylinder length="${thickness_lidar}" radius="${diam_lidar/2}" />
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${thickness_lidar}" radius="${diam_lidar/2}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass_lidar}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${mass_lidar}" r="${diam_lidar/2}" h="${thickness_lidar}" />
      </inertial>
    </link>

    <gazebo reference="${fb}_${cnc}_${lrc}_lidar">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="${fb}_${cnc}_${lrc}_lidar_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${fb}_${cnc}_${lrc}_lidar"/>
      <origin xyz="${translateX * base_x_origin_to_lidar_origin} ${translateY * base_y_origin_to_lidar_origin} ${base_z_origin_to_lidar_origin + (thickness_lidar/2) + translateZ}" rpy="0 0 0" /> 
    </joint>

    <!-- Transmission is important to link the joints and the controller -->
    <transmission name="${fb}_${cnc}_${lrc}_lidar_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fb}_${cnc}_${lrc}_lidar_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${fb}_${cnc}_${lrc}_lidar_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
   
  </xacro:macro>
</robot>
