<?xml version="1.0"?>
<robot name="raskar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- General purpose testing file -->

  <!-- Constants for robot dimensions -->
  <xacro:property name="Pi"              value="3.1415926535897931"/>
  <xacro:property name="mass_body"       value="68.0"  /> <!-- Mass of car        -->
  <xacro:property name="mass_wheel"      value="1.8"   /> <!-- Mass of wheel      -->
  <xacro:property name="mass_lidar"      value="0.1"   /> <!-- Mass of lidar      -->

  <xacro:property name="width_body"      value="0.628" /> <!-- Width of car       -->
  <xacro:property name="length_body"     value="0.948" /> <!-- Length of car      -->
  <xacro:property name="height_body"     value="0.282" /> <!-- Height of car      -->

  <xacro:property name="diam_wheel"      value="0.127" /> <!-- Diameter of wheel  -->
  <xacro:property name="thickness_wheel" value="0.066" /> <!-- Thickness of wheel -->

  <xacro:property name="diam_lidar"      value="0.075" /> <!-- Angle of lidar     -->
  <xacro:property name="thickness_lidar" value="0.045" /> <!-- Thickness of wheel -->

  <xacro:property name="safety_offset"   value="1.25"  /> <!-- Percentage safety  -->
  <xacro:property name="floor_clearance" value="0.0350"/> <!-- Floor clearance    -->
  <xacro:property name="model_offset"    value="0.0127"/> <!-- Floor clearance    -->

 
  <!-- Gazebo initializer -->
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find raskar_urdf)/urdf/raskar_params.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find raskar_urdf)/urdf/materials.xacro"      />

  <!-- Other mechanical elements -->
  <!-- Import Wheels -->
  <xacro:include filename="$(find raskar_urdf)/urdf/wheel.urdf.xacro" /> 
  <!-- Import Sensors -->
  <xacro:include filename="$(find raskar_urdf)/urdf/ultrasound.urdf.xacro" /> 
  <xacro:include filename="$(find raskar_urdf)/urdf/lidar.urdf.xacro" /> 


   <!-- Used for fixing robot to Gazebo -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <origin xyz="0 0 ${floor_clearance}" rpy="0 0 0" />
    <parent link="world"/>
    <child link="base_footprint"/>
  </joint>

  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${height_body/2}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!-- BASE-LINK -->
  <link name="base_link">
    <visual>
      <origin rpy="1.571 0 0" xyz="0 0 ${-height_body/2-floor_clearance-model_offset}"/>
      <geometry>	
        <mesh filename="package://raskar_urdf/meshes/body_parts.stl" scale="0.001 0.001 0.001" />	
      </geometry>
      <material name="pale_grey"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.25"/>
      <geometry>
        <!--box size="0.948 0.636 0.3"/-->
        <box size="0.998 0.678 0.35"/>
      </geometry>      
    </collision>
  </link>

  <!-- Wheels Definition -->

  <wheel fb="bk" lr="left"  parent="base_link" translateX="-1" translateY="-1" translateZ="${((-height_body/2)-floor_clearance)}" flipY="1"/>
  <wheel fb="fr" lr="left"  parent="base_link" translateX="1"  translateY="-1" translateZ="${((-height_body/2)-floor_clearance)}" flipY="1"/>
  <wheel fb="fr" lr="right" parent="base_link" translateX="1"  translateY="1"  translateZ="${((-height_body/2)-floor_clearance)}" flipY="1"/>
  <wheel fb="bk" lr="right" parent="base_link" translateX="-1" translateY="1"  translateZ="${((-height_body/2)-floor_clearance)}" flipY="1"/>


  <!-- Ultrasound sensors definition -->
  <ultrasound fb="fr" cnc="nocorner" lr="right"  parent="base_link" translateX="1" translateY="-1" translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="0"/>
  <ultrasound fb="fr" cnc="nocorner" lr="left"   parent="base_link" translateX="1" translateY="1"  translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="0"/>

  <ultrasound fb="fr" cnc="corner"   lr="right"  parent="base_link" translateX="0.8991870987"  translateY="-2.5038" translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="-45"/>
  <ultrasound fb="fr" cnc="corner"   lr="left"   parent="base_link" translateX="0.8991870987"  translateY="2.5038"  translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="45"/>

  <ultrasound fb="bk" cnc="corner"   lr="right"  parent="base_link" translateX="-0.8991870987" translateY="-2.5038" translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="225"/>
  <ultrasound fb="bk" cnc="corner"   lr="left"   parent="base_link" translateX="-0.8991870987" translateY="2.5038"  translateZ="${((-height_body/2)-floor_clearance)}" flipX="90" flipY="0" flipZ="90" rotateTheta="135"/>


  <!-- Lidar definition -->
  <lidar fb="fr"  cnc="nocorner"   lrc="center"  parent="base_link" translateX="1" translateY="1"  translateZ="${((-height_body/2)-floor_clearance)}" flipX="0" flipY="0" flipZ="0"/>


</robot>
