<?xml version="1.0"?>
<robot name="ultrasound" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Ultrasound sensors -->
  <property name="height_usound"    value="0.045" /> <!-- height of sensor  -->
  <property name="width_usound"     value="0.020" /> <!-- width of sensor   -->
  <property name="depth_usound"     value="0.015" /> <!-- length of sensor  -->
  <property name="mass_usound"      value="0.045" /> <!-- Mass of sensor    -->
  
  <property name="base_x_origin_to_ultrasound_origin" value="0.45639" />
  <property name="base_y_origin_to_ultrasound_origin" value="0.10000" />
  <property name="base_z_origin_to_ultrasound_origin" value="0.05400" />
  
  <macro name="cuboid_inertia" params="m h d w">
    <inertia  ixx="${m*(w*w+d*d)/12}" ixy = "0" ixz = "0"
              iyy="${m*(d*d+h*h)/12}" iyz = "0"
              izz="${m*(w*w+h*h)/12}" /> 
  </macro>
  
  <xacro:macro name="ultrasound" params="fb cnc lr parent translateX translateY translateZ flipX flipY flipZ"> <!--fb : front, back ; cnc: corner, no corner; lr: left, right -->
    <link name="${fb}_${cnc}_${lr}_ultrasound">
      <visual>
        <origin xyz="0 0 0" rpy="${flipX*Pi/180} 0 ${flipZ*Pi/180}"/> 
        <geometry>
          <!-- cylinder length="${thickness_ultrasound}" radius="${diam_ultrasound/2}" /-->
          <mesh filename="package://raskar_urdf/meshes/ultrasound_hc_sr04.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <!-- cylinder length="${thickness_ultrasound}" radius="${diam_ultrasound/2}" /-->
          <mesh filename="package://raskar_urdf/meshes/ultrasound_hc_sr04.stl" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass_usound}" />
        <origin xyz="0 0 0" />
        <cuboid_inertia  m="${mass_usound}" h="${height_usound}" d="${depth_usound}" w="${width_usound}" />
      </inertial>
    </link>

    <gazebo reference="${fb}_${cnc}_${lr}_ultrasound">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="${fb}_${cnc}_${lr}_ultrasound_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${fb}_${cnc}_${lr}_ultrasound"/>
      <origin xyz="${translateX * base_x_origin_to_ultrasound_origin} ${translateY * base_y_origin_to_ultrasound_origin} ${translateZ * base_z_origin_to_ultrasound_origin}" rpy="0 0 0" /> 
    </joint>

    <!-- Transmission is important to link the joints and the controller -->
    <transmission name="${fb}_${cnc}_${lr}_ultrasound_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fb}_${cnc}_${lr}_ultrasound_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${fb}_${cnc}_${lr}_ultrasound_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
   
  </xacro:macro>
</robot>
