<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Wheels -->
  <property name="diam_wheel"      value="0.127" /> <!-- Diameter of wheel  -->
  <property name="thickness_wheel" value="0.066" /> <!-- Thickness of wheel -->
  <property name="mass_wheel"      value="1.8"   /> <!-- Mass of wheel      -->
  
  <property name="base_x_origin_to_wheel_origin" value="0.260" />
  <property name="base_y_origin_to_wheel_origin" value="0.2670" />
  <property name="base_z_origin_to_wheel_origin" value="0.0635" />
  
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>
  
  <xacro:macro name="wheel" params="fb lr parent translateX translateY translateZ flipY"> <!--fb : front, back ; lr: left, right -->
    <link name="${fb}_${lr}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${flipY*Pi/2} 0  0 " /> 
        <geometry>
          <!-- cylinder length="${thickness_wheel}" radius="${diam_wheel/2}" /-->
          <mesh filename="package://raskar_urdf/meshes/5_in_mecanum.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="dark_yellow" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${flipY*Pi/2} 0 0 " />
        <geometry>
          <!-- cylinder length="${thickness_wheel}" radius="${diam_wheel/2}" /-->
          <mesh filename="package://raskar_urdf/meshes/5_in_mecanum.stl" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass_wheel}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${mass_wheel}" r="${diam_wheel/2}" h="${thickness_wheel}" />
      </inertial>
    </link>

    <gazebo reference="${fb}_${lr}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="${fb}_${lr}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${fb}_${lr}_wheel"/>
      <origin xyz="${translateX * base_x_origin_to_wheel_origin} ${translateY * base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin + translateZ}" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0  0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <!-- Transmission is important to link the joints and the controller -->
    <transmission name="${fb}_${lr}_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fb}_${lr}_wheel_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${fb}_${lr}_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
   
  </xacro:macro>
</robot>
